import { describe, it, expect } from "vitest";
import {
  inferAIProvenanceFromPullRequest,
  PROVENANCE_PACKAGE_VERSION,
} from "./index.js";

describe("@ai-sdlc/provenance", () => {
  it("exports package version", () => {
    expect(PROVENANCE_PACKAGE_VERSION).toBe("0.1.0");
  });

  it("infers developer-declared provenance from PR title", () => {
    const result = inferAIProvenanceFromPullRequest({
      title: "AI-assisted refactor generated by Claude Code",
      body: "This PR was created with AI assistance.",
    });

    expect(result.involvement).toBe("YES");
    expect(result.source).toBe("DEVELOPER_DECLARED");
    expect(result.agentName).toBe("Claude Code");
    expect(result.confidence).toBeCloseTo(0.94);
    expect(result.evidence).toHaveLength(1);
    expect(result.evidence[0]?.reason).toContain("Developer declaration");
  });

  it("returns UNKNOWN when no provenance signal is present", () => {
    const result = inferAIProvenanceFromPullRequest({
      title: "Fix login redirect",
      body: "This PR updates the auth flow and fixes an edge case.",
    });

    expect(result.involvement).toBe("UNKNOWN");
    expect(result.source).toBe("UNKNOWN");
    expect(result.confidence).toBe(0.5);
    expect(result.agentName).toBeUndefined();
  });
});
