/**
 * AI provenance and attribution package.
 * Phase 5+: AI involvement detection, confidence, provenance sources.
 */

export type ProvenanceSource =
  | "DEVELOPER_DECLARED"
  | "AGENT_TELEMETRY"
  | "GIT_METADATA"
  | "IDE_SIGNAL"
  | "BEHAVIORAL_INFERENCE"
  | "CI_SIGNAL"
  | "UNKNOWN";

export type AIInvolvement = "YES" | "NO" | "UNKNOWN";

export interface ProvenanceEvidence {
  reason: string;
  detail?: string;
}

export interface ProvenanceResult {
  /** YES / NO / UNKNOWN — never present inferred attribution as absolute truth */
  involvement: AIInvolvement;
  agentName?: string;
  modelName?: string;
  confidence: number;
  source: ProvenanceSource;
  evidence: ProvenanceEvidence[];
}

export interface GitHubPullRequestProvenancePayload {
  title?: string;
  body?: string | null;
  user?: { login?: string | null } | null;
  head?: { ref?: string | null; sha?: string | null } | null;
}

const AGENT_PATTERNS: Array<{ regex: RegExp; name: string }> = [
  { regex: /claude[- ]?code/i, name: "Claude Code" },
  { regex: /github copilot|copilot/i, name: "GitHub Copilot" },
  { regex: /codex/i, name: "Codex" },
  { regex: /gpt-?\d+/i, name: "GPT" },
  { regex: /chatgpt/i, name: "ChatGPT" },
];

const DECLARATION_PATTERNS: Array<RegExp> = [
  /ai-assisted/i,
  /generated by/i,
  /generated with/i,
  /ai generated/i,
  /ai-assisted/i,
  /assistant/i,
  /developer declared/i,
  /generated using/i,
  /using ai/i,
];

function normalizeText(value?: string | null): string {
  return (value ?? "").trim();
}

export function inferAIProvenanceFromPullRequest(
  payload: GitHubPullRequestProvenancePayload,
): ProvenanceResult {
  const title = normalizeText(payload.title);
  const body = normalizeText(payload.body);
  const candidateText = [title, body].filter(Boolean).join(" ");

  if (!candidateText) {
    return {
      involvement: "UNKNOWN",
      confidence: 0.5,
      source: "UNKNOWN",
      evidence: [{ reason: "No PR title or body available", detail: "Unable to infer provenance from empty text." }],
    };
  }

  const agentMatch = AGENT_PATTERNS.find((pattern) => pattern.regex.test(candidateText));
  const sourceMatch = DECLARATION_PATTERNS.some((pattern) => pattern.test(candidateText));

  if (sourceMatch) {
    const agentName = agentMatch?.name ?? "Unknown";
    const modelName = agentMatch ? undefined : undefined;
    const evidenceDetail = `Found developer-declared provenance marker in PR text.`;

    return {
      involvement: "YES",
      agentName,
      modelName,
      confidence: agentMatch ? 0.94 : 0.75,
      source: "DEVELOPER_DECLARED",
      evidence: [
        {
          reason: "Developer declaration detected",
          detail: evidenceDetail,
        },
      ],
    };
  }

  return {
    involvement: "UNKNOWN",
    confidence: 0.5,
    source: "UNKNOWN",
    evidence: [
      {
        reason: "No provenance signals matched",
        detail: "Falling back to UNKNOWN until more evidence is available.",
      },
    ],
  };
}

export const PROVENANCE_PACKAGE_VERSION = "0.1.0";
